# Generated by Django 4.1.1 on 2022-09-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=10)),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('draft', models.BooleanField(blank=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.category')),
            ],
        ),
    ]
